url: "https://zfu-lab.org"  #"https://zfu-lab.org"                #http://127.0.0.1:4000/ # the base hostname & protocol for your site, e.g. http://example.com
#url: "http://127.0.0.1:4000"
baseurl: "" # the subpath of your site, e.g. /blog
title: "Fu Lab" # the name of your site, e.g. ACME Corp.
description: "of human neuroscience"
